### ISSUE TITLE
How to install this gem in ruby 1.8.7?

### ISSUE THREAD

**Issue by chibeepatag** [xero-gateway/xero_gateway#109]
The archaic application I'm supporting runs on ruby 1.8.7 and there is no way for us to upgrade.
How can I install the xero_gateway gem in ruby 1.8.7?

I saw an old post [here](https://community.xero.com/developer/discussion/83001) so it must be possible. I tried 
gem install oauth -v 0.4.5
gem install i18n -v 0.6.11
gem install xero_gateway -v 2.0.14

but I upon installing xero_gateway I get i18n requires Ruby version >= 1.9.3.

Help please!

**Comment by nikz** [comment]
Hi Celine,

We're actually considering dropping support for Ruby `1.9.3` as it is no longer getting security updates, so `1.8.7` is very much not supported I'm afraid.

It's very unlikely that you'll continue to be able to maintain applications at 1.8.7, and I would strongly suggest you consider upgrading.

Otherwise, the only other suggestion I can make would be to attempt installation of a very old version of the gem - you might have lock some dependencies.

Cheers,

Nik

**Comment by chibeepatag** [comment]
Would you have a changelog? I need to find the oldest version that supports parter apps.

**Comment by armstrjare** [comment]
Not too far back, MinuteDock was on 1.8.7 until it was EOL'd. There haven't
been major changes from our end, so it will only be some of the
dependencies.

Jared
