### ISSUE TITLE
Gateway.expires_at is nil when authorizing from access

### ISSUE THREAD

**Issue by chibeepatag** [xero-gateway/xero_gateway#114]
gateway.authorize_from_access(atoken, asecret)
gateway.expires_at #returns nil

**Comment by nikz** [comment]
@chibeepatag I'm assuming this is for a Public (3-legged) app rather than a Private app?

**Comment by chibeepatag** [comment]
Partner app.

**Comment by nikz** [comment]
Can you look at the response from the Access Token request (you'll probably have to `bundle open` and stick in debugger statements, I'm not sure if a proxy like [Charles](https://www.charlesproxy.com) will work but you could try that). 

Also, I'm assuming you have renewable tokens rather than 30 minute tokens?

**Comment by nikz** [comment]
@chibeepatag I'm going to close this issue now, please re-open if you have a chance to provide the response from the Access Token request.
